In [1]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]

input = number_of_toes[0]

pred = neural_network(input, weight)
print(pred)

# input == "Information"
# weight == "Knowledge" Also interpreted as the measure of "sensitivity" between the network's input and prediction.

0.8500000000000001


# Predicting with Multiple Inputs

In [7]:
# Empty network with multiple inputs

def neural_network(input, weights):
    pred = weighted_sum(input, weights)
    return pred

weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 10, 9]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

# Perform a weighted-sum of inputs

def weighted_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i]*b[i]
    return output

# Run the network
nn_pred = neural_network(input, weights)
print(nn_pred)

0.9800000000000001


## Predicting with Multiple Inputs using Numpy()

In [1]:
import numpy as np
weights = np.array([0.1, 0.2, 0.0])

def neural_network(input, weights):
#     pred1 = input.dot(weights)
    pred2 = np.dot(input, weights)
#     return (pred1, pred2)
    return pred2

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
preds = neural_network(input, weights)
print(preds)

0.9800000000000001


# Predicting with Multiple Outputs

## Multiple Predictions using a Single Input

Use a single input to predict ratio of: happy or sad players, hurt players, predicted wins. The single input is any of teh the win-loss record of the team

In [7]:
weights = [0.3, 0.2, 0.9] # Corresponding to hurt, % wins, and happy/sad

def neural_network(input, weights):
    pred = ele_mult(input,weights)
    return pred

def ele_mult(number, vector): # Element-wise multiplication
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number*vector[i]
    return output

wlrec = [0.65, 0.8, 9.8, 0.9]
input = wlrec[0]

# Call the prediction function
print(neural_network(wlrec[0], weights))

[0.195, 0.13, 0.5850000000000001]


## Multiple Predictions with Multiple Inputs

In [19]:
weights = [[0.1, 0.1, -0.3], # [#toes, %win, #fans]*[#hurt, #win, #sad].Transpose()
           [0.1, 0.2, 0.0],
           [0.0, 1.3, 0.1]]

def neural_network(input, weights):
    pred = vector_matrx_mult(input,weights)
    return pred

# The following dataset is the current status at the beginning of each game for the first four games of the season.
# toes = current average number of toes per player
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes = [8.5, 8.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i]*b[i]
#         print(output)
    return output

def vector_matrx_mult(vector,matrix):
    assert(len(vector) == len(matrix))
    output = [0, 0, 0]
    for i in range(len(vector)):
        output[i] = w_sum(vector, matrix[i])
    return output

# Call the main function to get predictions
print(neural_network(input, weights))

[0.555, 0.9800000000000001, 0.9650000000000001]


# Predicting on Predictions

Neural Networks can be Stacked!

The outputs of one network can be fed as input into another network. One reason is that some datasets (image classification) might be too complex for a single weighted matrix.

Assume there is another layer of neural nets between the input layer and the output layer called a "hidden layer." Input -> Hidden and Hidden -> Output forms two networks
The inputs is passed to the hidden layer and the output of the hidden layer is fed to the output layers - all with assigned weights.

In [36]:
# Input to Hidden weights

ih_wgt = [[0.1, 0.2, -0.1], # [#toes, %win, #fans]*[#hid0, #hid1, #hid2].Transpose()
         [-0.1, 0.1, 0.9],
         [0.1, 0.4, 0.1]]

# Hidden to Output weights

hp_wgt = [[0.3, 0.1, -0.3], # [#hid0, %hid1, #hid2]*[#hurt, #win, #sad].Transpose()
         [0.1, 0.2, 0.0],
         [0.0, 1.3, 0.1]]

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vector_matrx_mult(input, weights[0])
    pred = vector_matrx_mult(input, weights[1])
    
def vector_matrx_mult(vector,matrix):
    assert(len(vector) == len(matrix))
    output = [0, 0, 0]
    for i in range(len(vector)):
        output[i] = w_sum(vector, matrix[i])
    return output
    
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i]*b[i]
#         print(output)
    return output

toes = [8.5, 8.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

print(neural_network(input, weights))

None


In [38]:
import numpy as np

ih_wgt = np.array([[0.1, 0.2, -0.1],
                   [-0.1, 0.1, 0.9],
                   [0.1, 0.4, 0.1]])

hp_wgt = np.array([[0.3, 0.1, -0.3],
                  [0.1, 0.2, 0.0],
                  [0.0, 1.3, 0.1]])

weights = [ih_wgt, hp_wgt]

toes = np.array([8.5, 8.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

def neural_network(input, weights):
    hid = np.dot(input, weights[0]) # Weights[0] is the matrix of weights from input to hidden
    pred = np.dot(hid, weights[1]) # weights[1] is the matrix of weights from hidden to output
    return pred

preds = neural_network(input, weights)
print(preds)

[ 0.496  0.351 -0.286]


# Begin: An Side playing with Numpy

In [50]:
import numpy as np

a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
             [4,5,6,7]])
d = np.zeros((2,4))
e = np.random.rand(2,5)

print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')
print(f'd: {d}')
print(f'e: {e}')
print('====================')
print(f'a*0.1: {a*0.1}')
print(f'c*0.2: {c*0.2}')
print(f'a*b: {a*b}')
print(f'a*b*0.2: {a*b*0.2}')
print(f'a*c: {a*c}')

a: [0 1 2 3]
b: [4 5 6 7]
c: [[0 1 2 3]
 [4 5 6 7]]
d: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
e: [[0.94788399 0.34016538 0.51598668 0.21932362 0.63637496]
 [0.42591096 0.60325927 0.36411056 0.13964996 0.94396211]]
a*0.1: [0.  0.1 0.2 0.3]
c*0.2: [[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
a*b: [ 0  5 12 21]
a*b*0.2: [0.  1.  2.4 4.2]
a*c: [[ 0  1  4  9]
 [ 0  5 12 21]]


# Begin: An Side playing with Numpy

# Gradient Descent

## Learning using the Hot and Cold Method

Here "Learning" is all about error attributionor the art of figuring out how each weight played its part in creating error.

In [53]:
weight = 0.1
lr = 0.01 # lr == Learning Rate

# An empty network
def neural_network(input, weights):
    prediction = input*weights
    return prediction

# Making a prediction and evaluating the error
number_of_toes = [8.5]
win_or_lost_binary = [1] # Won!!!
true = win_or_lost_binary[0]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(f'prediction is: {pred}')
error = (pred-true)**2
print(f'error is: {error}')



prediction is: 0.8500000000000001
error is: 0.022499999999999975
